puts "These are the students in my cohort at Makers Academy"
puts "------------"

puts "Abraham Thomas"
puts "Andrew Krahmal"
puts "Ayaz Goulamabasse"
puts "Berta Gutierrez"
puts "Biwek Shrestha"
puts "Colin Frankish"
puts "James Hunter"
puts "Jorja Tracy Hung"
puts "Kalle Malmiharju"
puts "Makis Otman"
puts "Megan Folsom"
puts "Mihai-Liviu Cojocar"
puts "Nabin Rai"
puts "Peter Saxton"
puts "Rolando Barbella"
puts "Roy Gardiner"
